### ISSUE TITLE
IndexError in the dnase_only.py

### ISSUE THREAD

**Issue by ytliu1985** [wkopp/janggu_usecases#1]
Thank you very much for developing this excellent tool and making the comprehensive tutorial!
I install Janggu in python 3.7, and run this command smoothly: python dna_only.py -inputpath {datadir} -path {outputdir}
But I got the IndexError when I run: python dnase_only.py -inputpath {datadir} -path {outputdir} 
####################
Test effect of DNASE on BAM files (region width and normalization)
dnase_run_tpm_orient_7_1
Traceback (most recent call last):
  File "dnase_only.py", line 58, in <module>
    res = objective(shared_space)
  File "/home/ubuntu/Janggu/01_jund_prediction/model_utils.py", line 105, in objective
    train_data, val_data, test_data = get_data(params)
  File "/home/ubuntu/Janggu/01_jund_prediction/data_utils.py", line 69, in get_data
    cache=True)
  File "/home/ubuntu/anaconda3/envs/janggu/lib/python3.7/site-packages/janggu/data/coverage.py", line 720, in create_from_bam
    verbose=verbose)
  File "/home/ubuntu/anaconda3/envs/janggu/lib/python3.7/site-packages/janggu/data/genomicarray.py", line 1191, in create_genomic_array
    verbose=verbose)
  File "/home/ubuntu/anaconda3/envs/janggu/lib/python3.7/site-packages/janggu/data/genomicarray.py", line 666, in __init__
    loader(self)
  File "/home/ubuntu/anaconda3/envs/janggu/lib/python3.7/site-packages/janggu/data/coverage.py", line 229, in __call__
    array[pos, 1] += 1
**_IndexError: index 16569 is out of bounds for axis 0 with size 16569_**
Could you help me take a look? Thank you!

**Comment by wkopp** [comment]
Hi @ytliu1985,

sorry for the delay and thank you very much for reporting this issue!
I fixed the out of bounds issue in janggu version 0.10.1.

Best,
Wolfgang
